#!/bin/zsh

# This gets run for you via ~/Code/scripts/newSocketApp

sed s/bbbNAMEbbb/$1/g package.json > tst.json
rm package.json
mv tst.json package.json

sed s/bbbNAMEbbb/$1/g index.html > tst.html
rm index.html
mv tst.html index.html

sed s/bbbNAMEbbb/$1/g js/config.js > tst.js
rm js/config.js
mv tst.js js/config.js

sed s/bbbNAMEbbb/$1/g js/postVisit.js > tst.js
rm js/postVisit.js
mv tst.js js/postVisit.js

sudo ./npm_install
sudo npm install

npm run build

